---
language: bash
install:
  - bash <(curl -L https://github.com/vinsonchuong/bash-common-bundle-dependencies/raw/master/bin/bundle-dependencies)
  - export PATH=$PWD/packages/bin:$PATH
script:
  - bats spec
